sonar.projectKey=Namannn1869_AI-Resume-Analyzer
sonar.organization=harsh-dev1708
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/tests/**
sonar.test.inclusions=**/tests/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
